### ISSUE TITLE
0.1.0 Checklist

### ISSUE THREAD

**Issue by pabsantos** [ONSV/prfdata#1]
- [x] Atualizar os dados de 2023
- [x] Exportar os arquivos `.parquet`
- [x] Testar o uso dos dados
